name: Test Development

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - development

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: "gluo-meme-generator"

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          docker run --rm -v $PWD/apache/app:/app composer composer require aws/aws-sdk-php
          docker run --rm -v $PWD/apache/app:/app composer composer require microsoft/azure-storage-blob
          docker-compose --file docker-compose-test.yml build
          docker-compose --file docker-compose-test.yml up -d
          curl -si  http://localhost:8080/index.php | grep HTTP
          docker exec docker-memegen-aws_apache_1 php getMemes.php
          docker-compose --file docker-compose-test.yml down
